### ISSUE TITLE
开启creative-no-clip后发射器不能正常放置潜影盒

### ISSUE THREAD

**Issue by GLDYM** [LeavesMC/Leaves#161]
### 服务端版本 LeavesMC Version

git-Leaves-"67d10cd" (MC: 1.20.4)

### 预期的行为 Expected behavior

发射器正常放置潜影盒

### 观测到的实际行为 Observed/Actual behavior

发射器不能正常放置潜影盒

### 复现步骤 Steps/models to reproduce

- 输入 `/leaves config modify.creative-no-clip true` 开启创造无碰撞
- 放一个发射器，里面放个潜影盒，激活发射器，潜影盒无法发射

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (15):
Bukkit Plugins:
- AdvancedPortals, Essentials, EssentialsChat, EssentialsSpawn, FastAsyncWorldEdit, GSit, LuckPerms, PlaceholderAPI, ProtocolLib, spark
TAB, Vault, xaero-map-spigot

### 更多详细信息。 The more information.
log
```
[Server] [14:31:36 ERROR]: Error trying to place shulker box at BlockPosition{x=32, y=93, z=2}
[Server] java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.EntityHuman.canSpectatingPlace(net.minecraft.world.level.World, net.minecraft.world.level.block.state.IBlockData, net.minecraft.core.BlockPosition, net.minecraft.world.phys.shapes.VoxelShapeCollision)" because the return value of "net.minecraft.world.item.context.BlockActionContext.o()" is null
[Server]        at net.minecraft.world.item.BlockItem.canPlace(BlockItem.java:231) ~[?:?]
[Server]        at net.minecraft.world.item.BlockItem.getPlacementState(BlockItem.java:179) ~[?:?]
[Server]        at net.minecraft.world.item.BlockItem.place(BlockItem.java:80) ~[?:?]
[Server]        at net.minecraft.core.dispenser.ShulkerBoxDispenseBehavior.execute(ShulkerBoxDispenseBehavior.java:60) ~[?:?]
[Server]        at net.minecraft.core.dispenser.DefaultDispenseItemBehavior.dispense(DefaultDispenseItemBehavior.java:32) ~[?:?]
[Server]        at net.minecraft.world.level.block.DispenserBlock.dispenseFrom(DispenserBlock.java:109) ~[?:?]
[Server]        at net.minecraft.world.level.block.DispenserBlock.tick(DispenserBlock.java:136) ~[?:?]
[Server]        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.tick(BlockBehaviour.java:1276) ~[?:?]
[Server]        at net.minecraft.server.level.ServerLevel.tickBlock(ServerLevel.java:1373) ~[?:?]
[Server]        at net.minecraft.world.ticks.LevelTicks.runCollectedTicks(LevelTicks.java:197) ~[?:?]
[Server]        at net.minecraft.world.ticks.LevelTicks.tick(LevelTicks.java:94) ~[?:?]
[Server]        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:857) ~[?:?]
[Server]        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1700) ~[leaves-1.20.4.jar:git-Leaves-"08bc505"]
[Server]        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450) ~[leaves-1.20.4.jar:git-Leaves-"08bc505"]
[Server]        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1511) ~[leaves-1.20.4.jar:git-Leaves-"08bc505"]
[Server]        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1213) ~[leaves-1.20.4.jar:git-Leaves-"08bc505"]
[Server]        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[leaves-1.20.4.jar:git-Leaves-"08bc505"]
[Server]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by s-yh-china** [comment]
呜呜 修好了
