### ISSUE TITLE
Crash by a NPE while joining world.

### ISSUE THREAD

**Issue by qyl27** [LeavesMC/Leaves#169]
### 服务端版本 LeavesMC Version

git-Leaves-"f010a0c" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

玩家可以正常加入服务器。

### 观测到的实际行为 Observed/Actual behavior

服务器输出错误并关闭。

```
java.lang.NullPointerException: Cannot invoke "java.lang.ThreadLocal.get()" because "this.m" is null
	at net.minecraft.world.level.biome.Biome.getTemperature(Biome.java:147)
	at net.minecraft.world.level.biome.Biome.warmEnoughToRain(Biome.java:196)
	at net.minecraft.world.level.biome.Biome.shouldFreeze(Biome.java:169)
	at net.minecraft.world.level.biome.Biome.shouldFreeze(Biome.java:165)
	at net.minecraft.server.level.ServerLevel.tickPrecipitation(ServerLevel.java:1097)
	at net.minecraft.server.level.ServerLevel.tickChunk(ServerLevel.java:1041)
	at net.minecraft.server.level.ServerChunkCache.tickChunks(ServerChunkCache.java:660)
	at net.minecraft.server.level.ServerChunkCache.tick(ServerChunkCache.java:485)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:863)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1698)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:450)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1509)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

### 复现步骤 Steps/models to reproduce

把 Paper 服务端切换为 Leaves 服务端。

### 插件与数据包列表。 Plugin and Datapack List.

```
Server Plugins (46):
Paper Plugins:
EconomyShopGUI
Bukkit Plugins:
Back-Refactor, BookFrame, CatMessenger, ChatColor, CoreProtect, DiggusMaximusBukkit, Dispenser-Mining-Paper, EmojiChat, FreedomChat, GSit
Hat, Home, IconAtNight, LoreAnvil, LuckPerms, mcMMO, MeowilBox, MoreFurnaceRecipes, MorePotions, MoreStoneCuttingRecipes
Multiverse-Core, Multiverse-NetherPortals, Multiverse-Portals, PastryMaster, PlaceholderAPI, Plan, PlasmoVoice, PlugManX, ProtocolLib, pv-addon-broadcast
pv-addon-discs, pv-addon-groups, pv-addon-lavaplayer-lib, pv-addon-spectator, RealisticSeasons, RHEasyCrops, RHLeafDecay, SimpleTeleport, SkinsRestorer, spark
TakeTheCursesOff, Vault, VaultChatFormatter, VoidGen, XConomy
```

### 更多详细信息。 The more information.

我怀疑和 [server/0035-Use-aging-cache-for-biome-temperatures.patch](https://github.com/LeavesMC/Leaves/blob/master/patches/server/0035-Use-aging-cache-for-biome-temperatures.patch) 有关。

**Comment by s-yh-china** [comment]
无法复现，怪，把biome-temperatures-use-aging-cache会恢复正常吗

**Comment by LittleChest** [comment]
请发送完整日志

**Comment by qyl27** [comment]
> 请发送完整日志

https://pastebin.ubuntu.com/p/7ZnvJ2PMbZ/
