### ISSUE TITLE
无法使用插件“CommandWhitelist”

### ISSUE THREAD

**Issue by LittleChest** [LeavesMC/Leaves#19]
### 服务端版本 LeavesMC Version

git-Leaves-"cda924b"

### 预期的行为 Expected behavior

正常使用此插件（玩家只能看到所设置的命令）

### 观测到的实际行为 Observed/Actual behavior

加载插件时报错
[13:12:43 INFO]: [CommandWhitelist] Enabling CommandWhitelist v2.5.5
2023-01-30 13:12:43,881 Server thread ERROR Recursive call to appender Async
[13:12:43 ERROR]: Error occurred while enabling CommandWhitelist v2.5.5 (Is it up to date?)
java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class java.lang.String (java.util.LinkedHashMap and java.lang.String are in module java.base of loader 'bootstrap')
        at eu.endermite.commandwhitelist.common.ConfigCache.loadCWGroup(ConfigCache.java:128) ~[CommandWhitelist.jar:?]
        at eu.endermite.commandwhitelist.common.ConfigCache.reloadConfig(ConfigCache.java:99) ~[CommandWhitelist.jar:?]
        at eu.endermite.commandwhitelist.common.ConfigCache.<init>(ConfigCache.java:27) ~[CommandWhitelist.jar:?]
        at eu.endermite.commandwhitelist.bukkit.CommandWhitelistBukkit.reloadPluginConfig(CommandWhitelistBukkit.java:71) ~[CommandWhitelist.jar:?]
        at eu.endermite.commandwhitelist.bukkit.CommandWhitelistBukkit.onEnable(CommandWhitelistBukkit.java:37) ~[CommandWhitelist.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[leaves-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[leaves-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[leaves-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:580) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:494) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:639) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:438) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1106) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[leaves-1.19.3.jar:git-Leaves-"4eaa8f3"]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]

### 复现步骤 Steps/models to reproduce

1. 前往[CommandWhitelist下载页](https://modrinth.com/plugin/commandwhitelist)
2. 安装此插件
3. 报错且无法正常使用

### 插件与数据包列表。 Plugin and Datapack List.

Plugins (19): AntiOP, Chat2QQ, CommandWhitelist, CoreProtect, eBackup, floodgate, GlobalGamerules, LuckPerms, Matrix, MiraiMC, PlaceholderAPI, ProtocolLib, Scoreboard*, spark, Stp*, SystemProperties, ViaBackwards, ViaVersion, ViewSlimeChunk
There are 2 data packs enabled: [vanilla (built-in)], [file/bukkit (world)]

### 更多详细信息。 The more information.

附完整日志
[2023-01-30-4.log](https://github.com/LeavesMC/Leaves/files/10532494/2023-01-30-4.log)

**Comment by LittleChest** [comment]
配置文件有误无法加载 打扰了 抱歉
