### ISSUE TITLE
BotActionEvent是损坏的

### ISSUE THREAD

**Issue by serverbread** [LeavesMC/Leaves#199]
### 服务端版本 LeavesMC Version

git-Leaves-"1e3a70e" (MC: 1.20.4)

### 预期的行为 Expected behavior

使用skript + skript-reflect 运行如下脚本时没有任何错误：

```
import:
    top.leavesmc.leaves.event.bot.BotActionEvent

on BotActionEvent:
    broadcast "114514"
```

### 观测到的实际行为 Observed/Actual behavior

运行上述脚本skript出现了致命错误：

```
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! [Skript] Severe Error:
[00:10:53 ERROR]: #!#! An error occurred while trying to postLoad a Structure.
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Something went horribly wrong with Skript.
[00:10:53 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[00:10:53 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[00:10:53 ERROR]: #!#! Here is full list of them:
[00:10:53 ERROR]: #!#! skript-reflect v2.4 (https://github.com/SkriptLang/skript-reflect) 
[00:10:53 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[00:10:53 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[00:10:53 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[00:10:53 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[00:10:53 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[00:10:53 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Stack trace:
[00:10:53 ERROR]: #!#! org.bukkit.plugin.IllegalPluginAccessException: org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event top.leavesmc.leaves.event.bot.BotEvent. Static getHandlerList method required!
[00:10:53 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.getEventListeners(PaperEventManager.java:113)
[00:10:53 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperEventManager.registerEvent(PaperEventManager.java:103)
[00:10:53 ERROR]: #!#!     at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvent(PaperPluginManagerImpl.java:141)
[00:10:53 ERROR]: #!#!     at org.bukkit.plugin.SimplePluginManager.registerEvent(SimplePluginManager.java:704)
[00:10:53 ERROR]: #!#!     at skript-reflect.jar//org.skriptlang.reflect.java.elements.events.EvtByReflection.postLoad(EvtByReflection.java:120)
[00:10:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.structures.StructEvent.postLoad(StructEvent.java:79)
[00:10:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$9(ScriptLoader.java:589)
[00:10:53 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1756)
[00:10:53 ERROR]: #!#!     at java.base/java.util.ArrayList.removeIf(ArrayList.java:1744)
[00:10:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.lambda$loadScripts$10(ScriptLoader.java:581)
[00:10:53 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
[00:10:53 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
[00:10:53 ERROR]: #!#!     at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2200)
[00:10:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:511)
[00:10:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:457)
[00:10:53 ERROR]: #!#!     at Skript.jar//ch.njol.skript.SkriptCommand.onCommand(SkriptCommand.java:190)
[00:10:53 ERROR]: #!#!     at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:10:53 ERROR]: #!#!     at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146)
[00:10:53 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:1004)
[00:10:53 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchServerCommand(CraftServer.java:989)
[00:10:53 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.bk(DedicatedServer.java:504)
[00:10:53 ERROR]: #!#!     at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:452)
[00:10:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1519)
[00:10:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[00:10:53 ERROR]: #!#!     at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:314)
[00:10:53 ERROR]: #!#!     at java.base/java.lang.Thread.run(Thread.java:1570)
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Version Information:
[00:10:53 ERROR]: #!#!   Skript: 2.8.4 (latest)
[00:10:53 ERROR]: #!#!     Flavor: skriptlang-github
[00:10:53 ERROR]: #!#!     Date: 11:03:52.948789700
[00:10:53 ERROR]: #!#!   Bukkit: 1.20.4-R0.1-SNAPSHOT
[00:10:53 ERROR]: #!#!   Minecraft: 1.20.4
[00:10:53 ERROR]: #!#!   Java: 22 (OpenJDK 64-Bit Server VM 22+36)
[00:10:53 ERROR]: #!#!   OS: Linux amd64 6.8.2-zen2-1-zen
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Server platform: Spigot
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Current node: on BotActionEvent: (event-test.sk, line 4)
[00:10:53 ERROR]: #!#! Current item: null
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Thread: Server thread
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! Language: english
[00:10:53 ERROR]: #!#! Link parse mode: DISABLED
[00:10:53 ERROR]: #!#! 
[00:10:53 ERROR]: #!#! End of Error.
[00:10:53 ERROR]: #!#! 
```

### 复现步骤 Steps/models to reproduce

创建一个sk脚本放在``` plugins/Skript/scripts ```
sk内输入以下代码：

```
import:
    top.leavesmc.leaves.event.bot.BotActionEvent

on BotActionEvent:
    broadcast "114514"
```
然后输入``` /sk reload <path/to/xxx.sk> ```
报错

### 插件与数据包列表。 Plugin and Datapack List.

[00:22:03 INFO]: ------------=[ ServerUtils Plugins ]=-------------
[00:22:03 INFO]:  Plugins (8): CMILib, FastAsyncWorldEdit, LuckPerms, Residence, ServerUtils, Skript, skript-reflect and spark
[00:22:03 INFO]: -------------------------------------------------

[00:22:39 INFO]: There are 1 data pack(s) enabled: [vanilla (built-in)]
[00:22:39 INFO]: There are 1 data pack(s) available: [file/bukkit (world)]

### 更多详细信息。 The more information.

经过试验发现，错误是在``` on BotActionEvent: ```时导致的，如果不对此事件监听是不会触发任何错误的。

监听BotEvent同样会报错。

监听同样继承BotEvent的BotInventoryOpenEvent不发生报错。

监听BotCreateEvent、BotJoinEvent未发生报错。

由于报错只发生在这几个地方，因此我确信这是leaves的问题，并提交这个issue

**Comment by Bluemangoo** [comment]
assigned serverbread 😋
