### ISSUE TITLE
1.20.4最新版服务端更改leaves.yml里支持mod的配置文件玩家进入就掉线

### ISSUE THREAD

**Issue by boliang-yes** [LeavesMC/Leaves#230]
### 服务端版本 LeavesMC Version

Leaves-e7c14b8 leaves-1.20.4.jar

### 预期的行为 Expected behavior

1

### 观测到的实际行为 Observed/Actual behavior

进入服务器移动并挖了下方块就掉线

### 复现步骤 Steps/models to reproduce

[latest.log](https://github.com/user-attachments/files/15857959/latest.log)
![{30EC0504-4A96-4278-B59B-CA3B10C039A7}](https://github.com/LeavesMC/Leaves/assets/66565126/23b5626c-d2a4-4a9b-9b65-08e1f7f513ed)
![{68B7F2BC-38ED-4a5e-A0E4-C861328C0DF3}](https://github.com/LeavesMC/Leaves/assets/66565126/e397fcb5-6118-42f9-8db8-ad78f7bb9fb8)
![{A1256B76-A7E5-4815-9BAA-FC5B983C8BD6}](https://github.com/LeavesMC/Leaves/assets/66565126/405183af-43eb-47a5-9367-a3839b606ebc)

### 插件与数据包列表。 Plugin and Datapack List.

无任何插件数据包

### 更多详细信息。 The more information.

[20:12:18 INFO]: 111111joined the game
[20:12:18 INFO]: 111111[/111111:1111] logged in with entity id 440 at ([world]-3.5, 127.0, -7.5)
[20:12:18 INFO]: [Leaves] Player Dai_Yi_Ren_ joined with carpet 1.4.128+v231205
[20:12:31 WARN]: java.lang.reflect.InvocationTargetException
[20:12:31 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[20:12:31 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
[20:12:31 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:12:31 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[20:12:31 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[20:12:31 WARN]:        at top.leavesmc.leaves.protocol.core.LeavesProtocolManager.getPayload(LeavesProtocolManager.java:145)
[20:12:31 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:24)
[20:12:31 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.<init>(ServerboundCustomPayloadPacket.java:18)
[20:12:31 WARN]:        at net.minecraft.network.EnumProtocol$b.a(EnumProtocol.java:595)
[20:12:31 WARN]:        at net.minecraft.network.EnumProtocol$a.a(EnumProtocol.java:541)
[20:12:31 WARN]:        at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:30)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
[20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:12:31 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:12:31 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:12:31 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
[20:12:31 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
[20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
[20:12:31 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
[20:12:31 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
[20:12:31 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
[20:12:31 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
[20:12:31 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[20:12:31 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[20:12:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
[20:12:31 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(34) + length(4) exceeds writerIndex(36): PooledUnsafeDirectByteBuf(ridx: 34, widx: 36, cap: 36)
[20:12:31 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
[20:12:31 WARN]:        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809)
[20:12:31 WARN]:        at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:856)
[20:12:31 WARN]:        at net.minecraft.network.PacketDataSerializer.readFloat(PacketDataSerializer.java:1318)
[20:12:31 WARN]:        at top.leavesmc.leaves.protocol.JadeProtocol$RequestEntityPayload.<init>(JadeProtocol.java:544)
[20:12:31 WARN]:        ... 49 more
[20:12:31 INFO]: 111111lost connection: Payload [request_entity] from [jade] error
[20:12:31 INFO]: 111111left the game

**Comment by s-yh-china** [comment]
经典老番 让玩家更新jade就行了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月16日(周日) 晚上8:27
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [LeavesMC/Leaves] 1.20.4最新版服务端更改leaves.yml里支持mod的配置文件玩家进入就掉线 (Issue #230)




 
服务端版本 LeavesMC Version
 
Leaves-e7c14b8 leaves-1.20.4.jar
 
预期的行为 Expected behavior
 
1
 
观测到的实际行为 Observed/Actual behavior
 
进入服务器移动并挖了下方块就掉线
 
复现步骤 Steps/models to reproduce
 
latest.log
 30EC0504-4A96-4278-B59B-CA3B10C039A7.png (view on web)
 68B7F2BC-38ED-4a5e-A0E4-C861328C0DF3.png (view on web)
 A1256B76-A7E5-4815-9BAA-FC5B983C8BD6.png (view on web)
 
插件与数据包列表。 Plugin and Datapack List.
 
无任何插件数据包
 
更多详细信息。 The more information.
 
[20:12:18 INFO]: 111111joined the game
 [20:12:18 INFO]: 111111[/111111:1111] logged in with entity id 440 at ([world]-3.5, 127.0, -7.5)
 [20:12:18 INFO]: [Leaves] Player Dai_Yi_Ren_ joined with carpet 1.4.128+v231205
 [20:12:31 WARN]: java.lang.reflect.InvocationTargetException
 [20:12:31 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
 [20:12:31 WARN]:        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
 [20:12:31 WARN]:        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
 [20:12:31 WARN]:        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
 [20:12:31 WARN]:        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
 [20:12:31 WARN]:        at top.leavesmc.leaves.protocol.core.LeavesProtocolManager.getPayload(LeavesProtocolManager.java:145)
 [20:12:31 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.a(ServerboundCustomPayloadPacket.java:24)
 [20:12:31 WARN]:        at net.minecraft.network.protocol.common.ServerboundCustomPayloadPacket.(ServerboundCustomPayloadPacket.java:18)
 [20:12:31 WARN]:        at net.minecraft.network.EnumProtocol$b.a(EnumProtocol.java:595)
 [20:12:31 WARN]:        at net.minecraft.network.EnumProtocol$a.a(EnumProtocol.java:541)
 [20:12:31 WARN]:        at net.minecraft.network.PacketDecoder.decode(PacketDecoder.java:30)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
 [20:12:31 WARN]:        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 [20:12:31 WARN]:        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 [20:12:31 WARN]:        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 [20:12:31 WARN]:        at io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
 [20:12:31 WARN]:        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
 [20:12:31 WARN]:        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
 [20:12:31 WARN]:        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
 [20:12:31 WARN]:        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
 [20:12:31 WARN]:        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509)
 [20:12:31 WARN]:        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407)
 [20:12:31 WARN]:        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
 [20:12:31 WARN]:        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 [20:12:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:840)
 [20:12:31 WARN]: Caused by: java.lang.IndexOutOfBoundsException: readerIndex(34) + length(4) exceeds writerIndex(36): PooledUnsafeDirectByteBuf(ridx: 34, widx: 36, cap: 36)
 [20:12:31 WARN]:        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442)
 [20:12:31 WARN]:        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:809)
 [20:12:31 WARN]:        at io.netty.buffer.AbstractByteBuf.readFloat(AbstractByteBuf.java:856)
 [20:12:31 WARN]:        at net.minecraft.network.PacketDataSerializer.readFloat(PacketDataSerializer.java:1318)
 [20:12:31 WARN]:        at top.leavesmc.leaves.protocol.JadeProtocol$RequestEntityPayload.(JadeProtocol.java:544)
 [20:12:31 WARN]:        ... 49 more
 [20:12:31 INFO]: 111111lost connection: Payload [request_entity] from [jade] error
 [20:12:31 INFO]: 111111left the game

**Comment by GLDYM** [comment]
更新你的Jade。

**Comment by boliang-yes** [comment]
好的，谢谢麻烦了= - =
