### ISSUE TITLE
[1.20.6]Error on PacketInEvent.

### ISSUE THREAD

**Issue by YuanYuanOwO** [LeavesMC/Leaves#240]
### 服务端版本 LeavesMC Version

Leaves version 1.20.6-215-master@e234432

### 预期的行为 Expected behavior

报错不应在控制台刷屏

### 观测到的实际行为 Observed/Actual behavior

报错刷屏，以下是相关内容，实际似乎并未影响到什么

```
[01:50:38 ERROR]: Error on PacketInEvent.
java.lang.IndexOutOfBoundsException: readerIndex: 26, writerIndex: 13 (expected: 0 <= readerIndex <= writerIndex <= capacity(13))
        at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1087) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]
        at net.minecraft.network.FriendlyByteBuf.writeBytes(FriendlyByteBuf.java:1326) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.protocol.common.custom.DiscardedPayload.lambda$codec$0(DiscardedPayload.java:11) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:38) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:50) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:72) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at org.leavesmc.leaves.bytebuf.internal.InternalBytebufHandler.createBytebufPacket(InternalBytebufHandler.java:222) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at org.leavesmc.leaves.bytebuf.internal.InternalBytebufHandler$PacketHandler.write(InternalBytebufHandler.java:83) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
        at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib (2).jar:?]
        at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib (2).jar:?]
        at net.minecraft.network.Connection.doSendPacket(Connection.java:514) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:499) ~[leaves-1.20.6.jar:1.20.6-215-e234432]
        at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib (2).jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

### 复现步骤 Steps/models to reproduce

不清楚，在升级1.20.6前没有该问题，1.20.4那会只有部分玩家在部分情况出现掉线情况（之前在Discord频道反馈过）

### 插件与数据包列表。 Plugin and Datapack List.

```
[02:04:47 INFO]: Server Plugins (52):
[02:04:47 INFO]: Paper Plugins:
[02:04:47 INFO]:  - HuskSync, MarriageMaster
[02:04:47 INFO]: Bukkit Plugins:
[02:04:47 INFO]:  - AntiEndermanMushroom, AntiPopup, BetterLogStrip, BetterRTP, BetterTridents, BlockLocker, BungeeTabListPlus, Chunky, CMI, CMILib
[02:04:47 INFO]:  CoreProtect, DiscordSRV, FancyCropTrample, GlobalMarketPlus, GSit, ImageFrame, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, *IronElevators
[02:04:47 INFO]:  *KeepItems, LiteBans, Lootin, LuckPerms, mcMMO, Multiverse-Core, OreBroadcast, PetMaster, PlaceholderAPI, PlugManX
[02:04:47 INFO]:  PremiumVanish, ProtocolLib, PvPManager, qsaddon-discordsrv, qsaddon-list, qscompat-worldedit, qssuite-limited, QuickShop-Hikari, Residence, RIABandwidthSaver
[02:04:47 INFO]:  spark, TrChat, TreeAssist, UserPrefix, Vault, VillagerTradeLimiter, WorldBorder, WorldEdit, WorldGuard, XConomy
datapack list
[02:04:49 INFO]: 已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）]
[02:04:49 INFO]: 已无更多可用的数据包
```

### 更多详细信息。 The more information.

N/A
暂无

**Comment by s-yh-china** [comment]
看起来像是ProtocolLib和服务端自带功能出现了一些冲突? 不太确定 明天看看



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 27, 2024 02:06 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [LeavesMC/Leaves] [1.20.6]Error on PacketInEvent. (Issue #240)




 
服务端版本 LeavesMC Version
 
Leaves version ***@***.***
 
预期的行为 Expected behavior
 
报错不应在控制台刷屏
 
观测到的实际行为 Observed/Actual behavior
 
报错刷屏，以下是相关内容，实际似乎并未影响到什么
 [01:50:38 ERROR]: Error on PacketInEvent. java.lang.IndexOutOfBoundsException: readerIndex: 26, writerIndex: 13 (expected: 0 <= readerIndex <= writerIndex <= capacity(13))         at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]         at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]         at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]         at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1087) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final]         at net.minecraft.network.FriendlyByteBuf.writeBytes(FriendlyByteBuf.java:1326) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.protocol.common.custom.DiscardedPayload.lambda$codec$0(DiscardedPayload.java:11) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:38) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:50) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:72) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at org.leavesmc.leaves.bytebuf.internal.InternalBytebufHandler.createBytebufPacket(InternalBytebufHandler.java:222) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at org.leavesmc.leaves.bytebuf.internal.InternalBytebufHandler$PacketHandler.write(InternalBytebufHandler.java:83) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]         at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]         at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]         at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib (2).jar:?]         at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib (2).jar:?]         at net.minecraft.network.Connection.doSendPacket(Connection.java:514) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:499) ~[leaves-1.20.6.jar:1.20.6-215-e234432]         at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib (2).jar:?]         at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final]         at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]         at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]         at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]  
复现步骤 Steps/models to reproduce
 
不清楚，在升级1.20.6前没有该问题，1.20.4那会只有部分玩家在部分情况出现掉线情况（之前在Discord频道反馈过）
 
插件与数据包列表。 Plugin and Datapack List.
 [02:04:47 INFO]: Server Plugins (52): [02:04:47 INFO]: Paper Plugins: [02:04:47 INFO]:  - HuskSync, MarriageMaster [02:04:47 INFO]: Bukkit Plugins: [02:04:47 INFO]:  - AntiEndermanMushroom, AntiPopup, BetterLogStrip, BetterRTP, BetterTridents, BlockLocker, BungeeTabListPlus, Chunky, CMI, CMILib [02:04:47 INFO]:  CoreProtect, DiscordSRV, FancyCropTrample, GlobalMarketPlus, GSit, ImageFrame, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, *IronElevators [02:04:47 INFO]:  *KeepItems, LiteBans, Lootin, LuckPerms, mcMMO, Multiverse-Core, OreBroadcast, PetMaster, PlaceholderAPI, PlugManX [02:04:47 INFO]:  PremiumVanish, ProtocolLib, PvPManager, qsaddon-discordsrv, qsaddon-list, qscompat-worldedit, qssuite-limited, QuickShop-Hikari, Residence, RIABandwidthSaver [02:04:47 INFO]:  spark, TrChat, TreeAssist, UserPrefix, Vault, VillagerTradeLimiter, WorldBorder, WorldEdit, WorldGuard, XConomy datapack list [02:04:49 INFO]: 已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）] [02:04:49 INFO]: 已无更多可用的数据包  
更多详细信息。 The more information.
 
N/A
 暂无

**Comment by Lumine1909** [comment]
可以先在配置文件中关掉packet event
![image](https://github.com/LeavesMC/Leaves/assets/133463833/db880d45-6a30-4d4b-bce1-bd1739598c5a)

**Comment by Lumine1909** [comment]
> 看起来像是ProtocolLib和服务端自带功能出现了一些冲突? 不太确定 明天看看
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Jun 27, 2024 02:06 AM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [LeavesMC/Leaves] [1.20.6]Error on PacketInEvent. (Issue #240) 服务端版本 LeavesMC Version Leaves version ***@***.*** 预期的行为 Expected behavior 报错不应在控制台刷屏 观测到的实际行为 Observed/Actual behavior 报错刷屏，以下是相关内容，实际似乎并未影响到什么 [01:50:38 ERROR]: Error on PacketInEvent. java.lang.IndexOutOfBoundsException: readerIndex: 26, writerIndex: 13 (expected: 0 <= readerIndex <= writerIndex <= capacity(13)) at io.netty.buffer.AbstractByteBuf.checkIndexBounds(AbstractByteBuf.java:112) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final] at io.netty.buffer.AbstractByteBuf.readerIndex(AbstractByteBuf.java:121) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final] at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1097) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final] at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1087) ~[netty-buffer-4.1.97.Final.jar:4.1.97.Final] at net.minecraft.network.FriendlyByteBuf.writeBytes(FriendlyByteBuf.java:1326) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.protocol.common.custom.DiscardedPayload.lambda$codec$0(DiscardedPayload.java:11) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.codec.StreamCodec$2.encode(StreamCodec.java:38) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.writeCap(CustomPacketPayload.java:38) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:50) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.protocol.common.custom.CustomPacketPayload$1.encode(CustomPacketPayload.java:29) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.codec.StreamCodec$4.encode(StreamCodec.java:72) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at org.leavesmc.leaves.bytebuf.internal.InternalBytebufHandler.createBytebufPacket(InternalBytebufHandler.java:222) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at org.leavesmc.leaves.bytebuf.internal.InternalBytebufHandler$PacketHandler.write(InternalBytebufHandler.java:83) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1015) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] at io.netty.channel.AbstractChannel.write(AbstractChannel.java:301) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final] at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:210) ~[ProtocolLib (2).jar:?] at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyChannelProxy.write(NettyChannelProxy.java:199) ~[ProtocolLib (2).jar:?] at net.minecraft.network.Connection.doSendPacket(Connection.java:514) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:499) ~[leaves-1.20.6.jar:1.20.6-215-e234432] at ProtocolLib (2).jar/com.comphenix.protocol.injector.netty.channel.NettyEventLoopProxy.lambda$proxyRunnable$2(NettyEventLoopProxy.java:49) ~[ProtocolLib (2).jar:?] at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:413) ~[netty-transport-classes-epoll-4.1.97.Final.jar:4.1.97.Final] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final] at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?] 复现步骤 Steps/models to reproduce 不清楚，在升级1.20.6前没有该问题，1.20.4那会只有部分玩家在部分情况出现掉线情况（之前在Discord频道反馈过） 插件与数据包列表。 Plugin and Datapack List. [02:04:47 INFO]: Server Plugins (52): [02:04:47 INFO]: Paper Plugins: [02:04:47 INFO]: - HuskSync, MarriageMaster [02:04:47 INFO]: Bukkit Plugins: [02:04:47 INFO]: - AntiEndermanMushroom, AntiPopup, BetterLogStrip, BetterRTP, BetterTridents, BlockLocker, BungeeTabListPlus, Chunky, CMI, CMILib [02:04:47 INFO]: CoreProtect, DiscordSRV, FancyCropTrample, GlobalMarketPlus, GSit, ImageFrame, InteractiveChat, InteractiveChatDiscordSrvAddon, InventoryRollbackPlus, *IronElevators [02:04:47 INFO]: *KeepItems, LiteBans, Lootin, LuckPerms, mcMMO, Multiverse-Core, OreBroadcast, PetMaster, PlaceholderAPI, PlugManX [02:04:47 INFO]: PremiumVanish, ProtocolLib, PvPManager, qsaddon-discordsrv, qsaddon-list, qscompat-worldedit, qssuite-limited, QuickShop-Hikari, Residence, RIABandwidthSaver [02:04:47 INFO]: spark, TrChat, TreeAssist, UserPrefix, Vault, VillagerTradeLimiter, WorldBorder, WorldEdit, WorldGuard, XConomy datapack list [02:04:49 INFO]: 已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）] [02:04:49 INFO]: 已无更多可用的数据包 更多详细信息。 The more information. N/A 暂无 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

看起来像是处理 ServerboundCustomPayloadPacket 时似的

**Comment by s-yh-china** [comment]
我们需要确认问题是否还存在

**Comment by MC-XiaoHei** [comment]
@YuanYuanOwO

**Comment by YuanYuanOwO** [comment]
我们服务器暂时似了，没有测试环境，可以关了issue或者有问题再开
