### ISSUE TITLE
假人无法使用动作 Entity threw exception

### ISSUE THREAD

**Issue by Alexw9217** [LeavesMC/Leaves#292]
### 服务端版本 LeavesMC Version

Leaves version 1.21-39-master@a7b7a1a (2024-08-03T04:53:19Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

假人正常使用动作

### 观测到的实际行为 Observed/Actual behavior

使用/bot action botname attack 10 -1时，假人消失不见，但仍然存在服务器，服务器后台报错。
[19:32:12 ERROR]: Entity threw exception at world:9388.028845712304,89.0,-22654.420249719147
java.util.NoSuchElementException: null
        at java.base/java.util.ArrayList.getFirst(ArrayList.java:439) ~[?:?]
        at org.leavesmc.leaves.bot.ServerBot.getTargetEntity(ServerBot.java:419) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at org.leavesmc.leaves.bot.agent.actions.AttackAction.doTick(AttackAction.java:29) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at org.leavesmc.leaves.bot.agent.BotAction.tryTick(BotAction.java:79) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at org.leavesmc.leaves.bot.ServerBot.tick(ServerBot.java:411) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1245) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.level.ServerLevel.lambda$tick$4(ServerLevel.java:732) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:39) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:709) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1794) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:477) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.jar:1.21-39-a7b7a1a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### 复现步骤 Steps/models to reproduce

召唤一个假人，右键打开他的背包给他一把剑，使用/bot action botname attack 10 -1后假人消失不见，使用/bot remove botname后也不掉落任何物品
![2024-08-04_19 38 18](https://github.com/user-attachments/assets/cdcdff7b-6e92-4e76-9777-5073b64aea04)
![2024-08-04_19 38 32](https://github.com/user-attachments/assets/9be94cf8-230d-455a-b78b-40c6ad184faf)

### 插件与数据包列表。 Plugin and Datapack List.

[19:39:45 INFO]: Server Plugins (13):
[19:39:45 INFO]: Bukkit Plugins:
[19:39:45 INFO]:  - AuthMe, ChainMining, Essentials, EssentialsChat, EssentialsProtect, EssentialsSpawn, Geyser-Spigot, GSit, lovelyCreeper, LuckPerms
[19:39:45 INFO]:  ViaBackwards, ViaVersion, WorldListTrashCan

**Comment by Lumine1909** [comment]
@s-yh-china 
![image](https://github.com/user-attachments/assets/a831cc53-4ce8-45c8-8f62-afa8ce5c9632)

**Comment by s-yh-china** [comment]
别骂了别骂了，晚上就修，或者谁发个pr

**Comment by Alexw9217** [comment]
![fe874278-5381-4dae-9fe9-022da3f400a9](https://github.com/user-attachments/assets/3b509b09-e3b3-4b07-9e73-245b8e0b7e3f)
另外在1.20.6版本中重力方块从末地祭坛出现而不是黑曜石平台这点能修吗？

**Comment by Lumine1909** [comment]
> ![fe874278-5381-4dae-9fe9-022da3f400a9](https://private-user-images.githubusercontent.com/63954910/354903743-3b509b09-e3b3-4b07-9e73-245b8e0b7e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzg2OTUsIm5iZiI6MTcyMjc3ODM5NSwicGF0aCI6Ii82Mzk1NDkxMC8zNTQ5MDM3NDMtM2I1MDliMDktZTNiMy00YjA3LTllNzMtMjQ1YjhlMGI3ZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlYjE3YmU4ZDRjNDQ1NDg4OTM5MjFkMTIxZjM4OWEzZjRlNTVlMTIzOWRkZGZmZWVhZDRkZjc2NGYwYTcxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o0JjIrA4pRlTWbMSeWCGq_eZSbzJMMiwqfitKxu6TT8) 另外在1.20.6版本中重力方块从末地祭坛出现而不是黑曜石平台这点能修吗？

1.21还有这个问题吗？有的话会修 没有就得打钱了（

**Comment by s-yh-china** [comment]
> ![fe874278-5381-4dae-9fe9-022da3f400a9](https://private-user-images.githubusercontent.com/63954910/354903743-3b509b09-e3b3-4b07-9e73-245b8e0b7e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzg4NTAsIm5iZiI6MTcyMjc3ODU1MCwicGF0aCI6Ii82Mzk1NDkxMC8zNTQ5MDM3NDMtM2I1MDliMDktZTNiMy00YjA3LTllNzMtMjQ1YjhlMGI3ZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTNiYTkzOGNiOWRhMTYzODc5YzQ4MDJlZDQ5N2RmMjMzNDY1OTNkZDZhZGU4Y2E5OTA5ZmVkNWRiMzE4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2DYUrE6QYJrcGo_52D-77gJUmmC-HqE-qvtmbjqCkP8) 另外在1.20.6版本中重力方块从末地祭坛出现而不是黑曜石平台这点能修吗？

https://github.com/LeavesMC/Leaves/issues/237
我觉得很类似，你可以看看

**Comment by Bluemangoo** [comment]
> ![fe874278-5381-4dae-9fe9-022da3f400a9](https://private-user-images.githubusercontent.com/63954910/354903743-3b509b09-e3b3-4b07-9e73-245b8e0b7e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3NzkyMjAsIm5iZiI6MTcyMjc3ODkyMCwicGF0aCI6Ii82Mzk1NDkxMC8zNTQ5MDM3NDMtM2I1MDliMDktZTNiMy00YjA3LTllNzMtMjQ1YjhlMGI3ZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzNDIwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNDNlYTNhOTAzZjVjMmE2MjIzMDU1MjZjYWVlNDliMTY2NGYwZTIwYzA4MjE2NmE3ODVlNmJjNWZjZmJlYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SBehHvNF_8UXDiMBqihOHFNs4nLR8slamWSFCDVb2ls) 另外在1.20.6版本中重力方块从末地祭坛出现而不是黑曜石平台这点能修吗？

参见 #237

**Comment by Alexw9217** [comment]
> > ![fe874278-5381-4dae-9fe9-022da3f400a9](https://private-user-images.githubusercontent.com/63954910/354903743-3b509b09-e3b3-4b07-9e73-245b8e0b7e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3Nzg4NTAsIm5iZiI6MTcyMjc3ODU1MCwicGF0aCI6Ii82Mzk1NDkxMC8zNTQ5MDM3NDMtM2I1MDliMDktZTNiMy00YjA3LTllNzMtMjQ1YjhlMGI3ZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA0VDEzMzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTNiYTkzOGNiOWRhMTYzODc5YzQ4MDJlZDQ5N2RmMjMzNDY1OTNkZDZhZGU4Y2E5OTA5ZmVkNWRiMzE4OTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2DYUrE6QYJrcGo_52D-77gJUmmC-HqE-qvtmbjqCkP8) 另外在1.20.6版本中重力方块从末地祭坛出现而不是黑曜石平台这点能修吗？
> 
> #237 我觉得很类似，你可以看看

确实是这个插件的问题 已经恢复

**Comment by Alexw9217** [comment]
> 别骂了别骂了，晚上就修，或者谁发个pr

更新后可以动作不会退出，但攻击无效，无伤害
![QQ20240804-234624](https://github.com/user-attachments/assets/5e4acfc5-6ecb-48cf-9ada-ddd5b35ffa1c)
