### ISSUE TITLE
插件[Spigot]Back不兼容

### ISSUE THREAD

**Issue by Mooling0602** [LeavesMC/Leaves#312]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-51-master@f552216 (2024-08-14T09:10:13Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### 预期的行为 Expected behavior

插件正常运行

### 观测到的实际行为 Observed/Actual behavior

插件报错，无法加载

### 复现步骤 Steps/models to reproduce

从Spigot下载安装最新版本的Back插件，然后启动服务器

### 插件与数据包列表。 Plugin and Datapack List.

> plugins
[Server] [20:38:18 INFO]: Server Plugins (10):
[Server] [20:38:18 INFO]: Bukkit Plugins:
[Server] [20:38:18 INFO]:  - AutoFishing, Back, BlockLocker, CoreProtect, DeathItems, floodgate, Geyser-Spigot, Hurricane, TabTPS, VeinMiner, ViaVersion

### 更多详细信息。 The more information.

[19:57:22] [Paper Plugin Remapper Thread - 3/INFO]: [PluginRemapper] Remapping plugin 'plugins/Back.jar'...
[19:57:22] [Paper Plugin Remapper Thread - 3/INFO]: [PluginRemapper] Done remapping plugin 'plugins/Back.jar' in 27ms.
[19:57:27] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'Back.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: me/GFelberg/Back/Main has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:129) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:550) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:296) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.UnsupportedClassVersionError: me/GFelberg/Back/Main has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:243) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:169) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
	at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
	at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:78) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:125) ~[leaves-1.21.1.jar:1.21.1-51-f552216]
	... 9 more

**Comment by s-yh-china** [comment]
.....不管我事 好好看报错

**Comment by Chenyu550** [comment]
Java版本不对
