### ISSUE TITLE
Grim反作弊不兼容

### ISSUE THREAD

**Issue by notwhitebear** [LeavesMC/Leaves#358]
### 服务端版本 LeavesMC Version

This server is running Leaves version 1.21.1-68-master@b33c46c (2024-10-12T05:25:53Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21.1-55-76d5ab8 (MC: 1.21.1)

### 预期的行为 Expected behavior

在使用Grimac使，普通玩家在地狱和末地应该可以正常移动

### 观测到的实际行为 Observed/Actual behavior

普通玩家在地狱和末地走几步就疯狂回弹（地狱尤其严重）

### 复现步骤 Steps/models to reproduce

加入grimac 2.3.66/67，使用一个没有grim.exempt权限的玩家进入地狱/末地
观察服务器报错和回弹情况

### 插件与数据包列表。 Plugin and Datapack List.

Server Plugins (42):
Bukkit Plugins:
 - AdvancedBan, BottledExp, Chunky, CMILib, combatag, *CommandBridge, DeathMessages, DeluxeMenus, Essentials, EssentialsChat, ExcellentEnchants, feedback, floodgate, GrimAC, GSit, GWarp, InteractiveBooks, Iris, KnockbackSync, LuckPerms, NBTAPI, nightcore, NoExperienceLossPlugin, NotTooExpensive, OpenInv, PlaceholderAPI, PlayerParticles, PlayerTitle, ProtocolLib, Residence, SpecialItemsPlugin, TAB, TAB-Bridge, tabblocker, TabTPS, *TPAPro, ViaBackwards, ViaRewind, ViaVersion, ViewDistanceTweaks, voicechat, WorldEdit

### 更多详细信息。 The more information.

事实上，我个人因为在学校无法对这个漏洞进行太多测试，所以这也可能是paper上游或我自身插件的问题，如果对你们造成了不必要的麻烦请谅解。

在玩家发生回弹时服务器出现以下警告：
[11:14:20 WARN]: [GrimAC] Task #1347 for GrimAC v2.3.66 generated an exception
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1019) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1009) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at org.bukkit.Bukkit.dispatchCommand(Bukkit.java:1114) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at grimac-2.3.66.jar/ac.grim.grimac.manager.PunishmentManager.lambda$handleAlert$2(PunishmentManager.java:164) ~[grimac-2.3.66.jar:?]
        at grimac-2.3.66.jar/ac.grim.grimac.shaded.io.github.retrooper.packetevents.util.folia.GlobalRegionScheduler.lambda$run$0(GlobalRegionScheduler.java:68) ~[grimac-2.3.66.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:79) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1720) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:478) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1596) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1303) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[leaves-1.21.1.jar:1.21.1-68-b33c46c]
        at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
        
 我没有更改任何关于Grim的配置，这里我使用的是2.3.66版本，但是经测试，最新的2.3.67也存在此问题。我不确定这是不是grim本身的问题，但是据它们所说：（https://www.spigotmc.org/resources/grim-anticheat.99923/updates）
 · Added support for 1.21 servers
所以我先到你们这里来反馈一下，如果你们可以确定这不是leaves的问题我将会去和他们反馈。

**Comment by MC-XiaoHei** [comment]
这玩意怎么也不能是我们的问题啊（x）
@s-yh-china 你觉得呢

**Comment by Lumine1909** [comment]
我无法复现
使用最新的leaves和2.3.67

**Comment by serverbread-DEV** [comment]
这应该是插件的问题，而非 Leaves 的。

能请你在上游测试一下吗？

**Comment by HaHaWTH** [comment]
grim的自动alert爆了，更新Grim后还有就反馈给GrimAC
